title: sneha's site
description: hello world.
baseurl: ""
url: "https://sneha-afk.github.io"

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown
kramdown:
  parse_block_html: true
  footnotes: true
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: text
    guess_lang: true
    start_line: 1
    block:
      line_numbers: true

highlighter: rouge
