title: sneha de
description: hello world.
baseurl: ""
url: "https://sneha-afk.github.io"

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "posts"
    values:
      layout: post

author:
  name: Sneha De
  github: sneha-afk
  linkedin: https://www.linkedin.com/in/sneha-de/

404:
  layout: default
  permalink: /404

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown
kramdown:
  parse_block_html: true
  footnotes: true
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    default_lang: text
    guess_lang: true
    start_line: 1
    block:
      line_numbers: true

highlighter: rouge

toc:
  min_level: 1
  max_level: 6
  list_class: toc
  list_id: toc
  sublist_class: toc-sublist
  item_class: toc-item
  item_prefix: toc-

header_navigation:
  - name: /home
    url: /
  - name: /resume
    url: /resume
  - name: /projects
    url: /projects
  - name: /posts
    url: /posts

footer_navigation:
  - name: /gallery
    url: /gallery
  - name: /github
    url: https://github.com/sneha-afk
  - name: /linkedin
    url: https://www.linkedin.com/in/sneha-de/

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE
  - bin/
